### ISSUE TITLE
Swift_Mailer:Module display issue password field

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-swift_mailer#4]
![1-26-2018 7-48-40 pm](https://user-images.githubusercontent.com/12632568/35466484-3f495b6c-02d2-11e8-9278-333d068b6f57.png)

**Comment by benkeen** [comment]
Actually this is working properly - but you're right, it's not not clear. You only need to enter the password field if you're changing it. 

For security reasons the page doesn't re-output the password into the page. It's pretty minimal security, admittedly, since the module necessarily has to store the password with two-way encryption in order to use it when making the SMTP connection. And also because the only person who could get access to that page in the first place is the administrator who'd have been the one who entered it in the first place.

How about I add a comment by the field saying "The password has been saved. Only re-enter the SMTP password here if you need to reset it." ?

**Comment by johnbleck3** [comment]
So that's a feature! Gottcha. Yeah, a simple field comment would clear that up.
